# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Auto-generated Dockerfile for URL Content Saver MCP Server

FROM node:lts-alpine AS builder

# set working directory
WORKDIR /app

# copy package manifests
COPY package.json package-lock.json ./

# install dependencies
RUN npm ci --ignore-scripts

# copy source code
COPY . .

# build the TypeScript project
RUN npm run build

# ----- Runtime image -----
FROM node:lts-alpine
WORKDIR /app

# copy built artifacts and dependencies
COPY --from=builder /app/package.json /app/package-lock.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist

# default to stdio transport
ENTRYPOINT ["node", "dist/index.js"]
