# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# set working directory
WORKDIR /app

# copy package and ts config
COPY package.json package-lock.json tsconfig.json ./

# copy source
COPY src ./src

# install dependencies and build
RUN npm install --ignore-scripts && npm run build

# default command to start stdio MCP server
CMD ["npm", "start"]
